### PR TITLE
GitHub Issue Form for Processing Requests

### PR DESCRIPTION
**Pull request by riverma**
## Purpose
- This PR proposes a GitHub Issue form template for standardizing OPERA processing requests.
## Proposed Changes
- [ADD] New template form
## Issues
- N/A
## Testing
- Tested at: https://github.com/riverma/opera-sds/issues/new/choose

### CODE REVIEW

**Comment by riverma** [comment]
Note, in addition to this template, I propose creating the following labels for easy sorting:
- needs-triage (automatically tagged - removed after ticket accepted or closed)
- processing-request (automatically tagged)
- queued (added by person who triages ticket after ticket accepted)
- in-progress (added by person who triages ticket after processing begins)
- ADT (added by person who triages ticket)
- PST (added by person who triages ticket)
- OPS (added by person who triages ticket)

**Comment by sjlewis-jpl** [comment]
@riverma - when do you envision the `OPS` venue being selected for a request?  Messing with our operations venue, or with the operators themselves, seems very risky.

The original intent of this form was for other teams to request runs for testing, or VnV, etc.  Are you wanting to use this for tracking on-demand requests for granules missed somehow in normal operations?

**Comment by sjlewis-jpl** [comment]
The software version fields seem odd.  It looks like someone can mix and match the SW versions, but they're not actually independent - each PCM version has specific PGE versions, and each PGE version has a specific SAS version.

Maybe we should just condense down to a single SW version, say, `Software Version`, or `SDS Version`, or `System Version`?

**Review by sjlewis-jpl — CHANGES_REQUESTED** [review]
Overall this form looks great.  There are a few small changes to make, in the bullet list below.

- [x] Remove PGE & PCM versions, replace with System Version
- [ ] Under "Share Results", specify that the DAAC option is for their UAT instance.  Also add a a note that requests in the OPS venue _will_ go to the DAAC (not a choice).
- [ ] Add a venue called `VnV` (or `InT`?), for requests related to SDS or System VnV.
- [ ] Add a subdirectory to capture previous runs, and include (at least to start) files representing the R1 validation dataset, and any others we have available.  These are reference-able in the Input Data field.  (If you prefer, I'm open to splitting this off into another PR)

**Comment by riverma** [comment]
> Overall this form looks great. There are a few small changes to make, in the bullet list below.
> 
> * [x]  Remove PGE & PCM versions, replace with System Version
> * [x]  Under "Share Results", specify that the DAAC option is for their UAT instance.  Also add a a note that requests in the OPS venue _will_ go to the DAAC (not a choice).
> * [x]  Add a venue called `VnV` (or `InT`?), for requests related to SDS or System VnV.

@sjlewis-jpl - take a look at the rendering and let me know what you think of the changes.

> > * [ ]  Add a subdirectory to capture previous runs, and include (at least to start) files representing the R1 validation dataset, and any others we have available.  These are reference-able in the Input Data field.  (If you prefer, I'm open to splitting this off into another PR)

Not sure about what you're requesting here? Add a subdirectory to what? A place in GitHub to store run results?

**Review by niarenaw — APPROVED** [review]
Looks great to me!

**Review by sjlewis-jpl — APPROVED** [review]

**Pull request merged**
